---
- hosts: production
  remote_user: developer

  vars:
    remote_basedir: /home/developer/sites/samworks-ffhs-deep-slumber-live
    project_id: samworks-ffhs-deep-slumber-live

  tasks:
  - name: Create Base Dir
    file:
      path: "{{ remote_basedir }}"
      state: directory

  - name: Copy assets
    synchronize:
      src: ./../frontend.tar.gz
      dest: "{{ remote_basedir }}"

  - name: Extract assets
    unarchive:
      src: "{{ remote_basedir }}/frontend.tar.gz"
      dest: "{{ remote_basedir }}/frontend"
      remote_src: yes